get:
  summary: Plugin list
  operationId: getPlugins
  description: |
    Get a list of all the plugins running on the server.

    > Required permission: plugin.list
  tags:
    - Plugin
  responses:
    403:
      $ref: "#/responses/403"
    200:
      description: List of plugins
      schema:
        title: PluginsResponse
        type: object
        properties:
          ok:
            $ref: "#/definitions/ok"
          plugins:
            type: array
            description: A list of plugins.
            items:
              $ref: "#/definitions/Plugin"
